((f (k6 x)
 (:+ (x 1) (v9)
     ((:fix ((k7 (k8) (:app k6 (k8))))
            (:app g (k7 v9))))))
 (f (k6 x)
 (:+ (x 1) (v9)
     ((:fix ((k7 (k8) (:app kA (k8)))
	     (kA (kB) (:app k6 (kB))))
            (:app g (k7 v9))))))

 (f (k6 x)
 (:+ (x 1) (v9)
     ((:fix ((kc (kd) (:app k6 (kd)))
             (k7 (k8) (:app kA (k8)))
	     (k10 (x0 x1) (:+ (x0 x1) (rv) ((:app kc (rv)))))
	     (kA (kB) (:app kc (kB))))
            (:app g (k7 v9))))))
	    )

